/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PayeeLocation { 
    id: string;
    payeeId: string;
    latitude: string;
    longitude: string;
    /**
     * Whether or not the payee location has been deleted.  Deleted payee locations will only be included in delta requests.
     */
    deleted: boolean;
}

