/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Payee { 
    id: string;
    name: string;
    /**
     * If a transfer payee, the account_id to which this payee transfers to
     */
    transferAccountId: string;
    /**
     * Whether or not the payee has been deleted.  Deleted payees will only be included in delta requests.
     */
    deleted: boolean;
}

