/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionDetail } from './transactionDetail';


export interface SaveTransactionsResponseData { 
    /**
     * The transaction ids that were saved
     */
    transactionIds: Array<string>;
    /**
     * If multiple transactions were specified, the transactions that were saved
     */
    transactions?: Array<TransactionDetail>;
    /**
     * If multiple transactions were specified, a list of import_ids that were not were created because of an existing import_id found on the same account
     */
    duplicateImportIds?: Array<string>;
    transaction?: TransactionDetail;
}

