/**
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduledSubTransaction } from './scheduledSubTransaction';
import { ScheduledTransactionSummary } from './scheduledTransactionSummary';


export interface ScheduledTransactionDetail { 
    id: string;
    /**
     * The first date for which the Scheduled Transaction was scheduled.
     */
    dateFirst: string;
    /**
     * The next date for which the Scheduled Transaction is scheduled.
     */
    dateNext: string;
    frequency: ScheduledTransactionDetail.FrequencyEnum;
    /**
     * The scheduled transaction amount in milliunits format
     */
    amount: number;
    memo: string;
    /**
     * The scheduled transaction flag
     */
    flagColor: ScheduledTransactionDetail.FlagColorEnum;
    accountId: string;
    payeeId: string;
    categoryId: string;
    /**
     * If a transfer, the account_id which the scheduled transaction transfers to
     */
    transferAccountId: string;
    /**
     * Whether or not the scheduled transaction has been deleted.  Deleted scheduled transactions will only be included in delta requests.
     */
    deleted: boolean;
    accountName: string;
    payeeName: string;
    categoryName: string;
    /**
     * If a split scheduled transaction, the subtransactions.
     */
    subtransactions: Array<ScheduledSubTransaction>;
}
export namespace ScheduledTransactionDetail {
    export type FrequencyEnum = 'never' | 'daily' | 'weekly' | 'everyOtherWeek' | 'twiceAMonth' | 'every4Weeks' | 'monthly' | 'everyOtherMonth' | 'every3Months' | 'every4Months' | 'twiceAYear' | 'yearly' | 'everyOtherYear';
    export const FrequencyEnum = {
        Never: 'never' as FrequencyEnum,
        Daily: 'daily' as FrequencyEnum,
        Weekly: 'weekly' as FrequencyEnum,
        EveryOtherWeek: 'everyOtherWeek' as FrequencyEnum,
        TwiceAMonth: 'twiceAMonth' as FrequencyEnum,
        Every4Weeks: 'every4Weeks' as FrequencyEnum,
        Monthly: 'monthly' as FrequencyEnum,
        EveryOtherMonth: 'everyOtherMonth' as FrequencyEnum,
        Every3Months: 'every3Months' as FrequencyEnum,
        Every4Months: 'every4Months' as FrequencyEnum,
        TwiceAYear: 'twiceAYear' as FrequencyEnum,
        Yearly: 'yearly' as FrequencyEnum,
        EveryOtherYear: 'everyOtherYear' as FrequencyEnum
    };
    export type FlagColorEnum = 'red' | 'orange' | 'yellow' | 'green' | 'blue' | 'purple';
    export const FlagColorEnum = {
        Red: 'red' as FlagColorEnum,
        Orange: 'orange' as FlagColorEnum,
        Yellow: 'yellow' as FlagColorEnum,
        Green: 'green' as FlagColorEnum,
        Blue: 'blue' as FlagColorEnum,
        Purple: 'purple' as FlagColorEnum
    };
}

